Traceback (most recent call last):
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\krist\mambaforge\envs\jupyter_book_trial\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import os
from os.path import dirname, abspath, join

import pandas as pd

import helper

path_to_data = join(dirname(abspath('')), 'data')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 5[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mos[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpath[39;00m [38;5;28;01mimport[39;00m dirname, abspath, join
[1;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mhelper[39;00m
[0;32m      9[0m path_to_data [38;5;241m=[39m join(dirname(abspath([38;5;124m'[39m[38;5;124m'[39m)), [38;5;124m'[39m[38;5;124mdata[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

